GENERAL_LOG_FLAG = True
GENERAL_LOG_STDOUT_FLAG = True
GENERAL_LOG_TIMINGS_FLAG = True
LOGGING_ALLOW_GRAPHS = True
LOGGING_VERBOSITY = 3

PERFORMANCE_MONITORING_DIR_PATH = 'performance_monitoring'
LOG_IMAGES_DIR_PATH = 'images'

CSV_FILENAME_EXTENSION_FUNCTION_TIMES_CSV = 'function_times'
CSV_FILENAME_EXTENSION_LOGS_CSV = 'logs'
