

DB_EXPERIMENT_TABLE_NAME_COL_EXPID = "experiment_id"
DB_EXPERIMENT_TABLE_NAME_COL_EPISODES = "episodes"
DB_EXPERIMENT_TABLE_NAME_COL_STEPS = "steps_list"
DB_EXPERIMENT_TABLE_NAME_COL_STATES = "states"
DB_EXPERIMENT_TABLE_NAME_COL_NEXTSTATES = "next_states"
DB_EXPERIMENT_TABLE_NAME_COL_ACTIONS = "actions"
DB_EXPERIMENT_TABLE_NAME_COL_REWARDS = "rewards"
DB_EXPERIMENT_TABLE_NAME_COL_DONE = "dones"


DATA_COLUMNS = [DB_EXPERIMENT_TABLE_NAME_COL_EPISODES,
                DB_EXPERIMENT_TABLE_NAME_COL_STEPS,
                DB_EXPERIMENT_TABLE_NAME_COL_STATES,
                DB_EXPERIMENT_TABLE_NAME_COL_NEXTSTATES,
                DB_EXPERIMENT_TABLE_NAME_COL_ACTIONS,
                DB_EXPERIMENT_TABLE_NAME_COL_REWARDS,
                DB_EXPERIMENT_TABLE_NAME_COL_DONE]
